version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:8080"
    environment:
      - PORT=8080
    env_file:
      - .env
    volumes:
      # Mount source code for development (optional)
      # - ./backend:/app
      # - ./static:/app/static
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  # Optional: Add Firebase emulator for local development
  firebase-emulator:
    image: node:18-alpine
    command: >
      sh -c "
        npm install -g firebase-tools &&
        firebase emulators:start --only firestore --import=./emulator-data --export-on-exit
      "
    ports:
      - "8080:8080"  # Firestore emulator
      - "4000:4000"  # Firebase UI
    volumes:
      - ./firebase.json:/firebase.json
      - ./firestore.rules:/firestore.rules
      - ./firestore.indexes.json:/firestore.indexes.json
      - firebase-data:/emulator-data
    environment:
      - FIREBASE_PROJECT=frl-wb
    networks:
      - app-network
    profiles:
      - emulator

networks:
  app-network:
    driver: bridge

volumes:
  firebase-data:
